export const SCENES = {
  boot: 'Boot',
  preload: 'Preload',
  menu: 'Menu',
  fileSelect: 'FileSelect',
  difficulty: 'Difficulty',
  chapterSelect: 'ChapterSelect',
  level: 'Level',
  ui: 'UI',
  pause: 'Pause',
  gameOver: 'GameOver',
  chapterComplete: 'ChapterComplete',
  actEnd: 'ActEnd',
  gallery: 'Gallery',
  settings: 'Settings',
  touch: 'Touch',
} as const;
