import { PALETTE as P } from '../../config/palette';
import { TILESET_FRAME_COUNT } from '../../levels/tiles';
import { BEN_FRAME, BEN_FRAME_COUNT, BEN_FRAMES, drawBen } from './characters';
import { one, sheet, type AnimDef, type AssetDef } from './assetTypes';
import {
  BOSS_HULL,
  drawBossArm,
  drawBossEye,
  drawBossHull,
  drawBossPlate,
  drawBossTopPlate,
  drawArmored,
  drawGunner,
  drawHornet,
  drawScout,
  drawStriker,
} from './enemies';
import * as fx from './effects';
import * as props from './props';
import * as story from './story';
import * as ui from './uiArt';
import * as world from './world';
import { SILHOUETTE_ASSETS } from './silhouettes';
import * as hw from './highway';
import * as veh from './vehicles';
import * as portraits from './portraits';
import * as rb from './roadbreaker';
import * as goo from './goo';
import * as mut from './mutants';
import * as mus from './museum';
import * as animo from './animo';
import * as tech from './tech';
import * as robots from './robots';
import * as city from './city';
import * as kevin from './kevin';
import * as sumo from './sumo';

/**
 * Keys for every shared texture (world, enemies, UI, human Ben). Each alien
 * declares its own textures in its art module; `catalog.ts` joins both into the
 * single list Preload loads. Today each one is generated in code (`draw`). To
 * swap in real art, add a `url` (relative to public/) with the same frame size
 * and frame order; nothing else changes.
 */
export const TEX = {
  ben: 'ben',
  benNoWatch: 'ben-nowatch',
  scout: 'drone-scout',
  striker: 'drone-striker',
  gunner: 'drone-gunner',
  armored: 'drone-armored',
  hornet: 'drone-hornet',
  bossHull: 'boss-hull',
  bossPlate: 'boss-plate',
  bossTopPlate: 'boss-top-plate',
  bossEye: 'boss-eye',
  bossArm: 'boss-arm',
  tiles: 'tiles',
  tilesSim: 'tiles-sim',
  simSky: 'bg-sim-sky',
  simGrid: 'bg-sim-grid',
  simTowers: 'bg-sim-towers',
  boulder: 'prop-boulder',
  dummy: 'prop-dummy',
  sky: 'bg-sky',
  stars: 'bg-stars',
  moon: 'bg-moon',
  mountains: 'bg-mountains',
  pinesFar: 'bg-pines-far',
  pinesMid: 'bg-pines-mid',
  fog: 'bg-fog',
  trunks: 'bg-trunks',
  crashGlow: 'bg-crash-glow',
  rv: 'prop-rv',
  tent: 'prop-tent',
  campfire: 'prop-campfire',
  log: 'prop-log',
  sign: 'prop-sign',
  bush: 'prop-bush',
  rock: 'prop-rock',
  stump: 'prop-stump',
  grass: 'prop-grass',
  mushroom: 'prop-mushroom',
  crater: 'prop-crater',
  wreck: 'prop-wreck',
  debris: 'prop-debris',
  burningLogs: 'prop-burning-logs',
  pod: 'prop-pod',
  omnitrixItem: 'prop-omnitrix',
  checkpoint: 'prop-checkpoint',
  smoothy: 'pickup-smoothy',
  card: 'pickup-card',
  jammer: 'prop-jammer',
  gate: 'prop-gate',
  arenaWall: 'prop-arena-wall',
  soft: 'fx-soft',
  light: 'fx-light',
  px: 'fx-px',
  spark: 'fx-spark',
  ember: 'fx-ember',
  smoke: 'fx-smoke',
  ring: 'fx-ring',
  rays: 'fx-rays',
  hourglass: 'fx-hourglass',
  fireball: 'fx-fireball',
  laser: 'fx-laser',
  bossBolt: 'fx-boss-bolt',
  shockwave: 'fx-shockwave',
  wave: 'fx-wave',
  streak: 'fx-streak',
  crack: 'fx-crack',
  needle: 'fx-needle',
  shell: 'fx-shell',
  bomb: 'fx-bomb',
  reticle: 'fx-reticle',
  beam: 'fx-beam',
  debrisBits: 'fx-debris',
  leaf: 'fx-leaf',
  shadow: 'fx-shadow',
  water: 'fx-water',
  whitePx: 'fx-white',
  heart: 'ui-heart',
  dialFrame: 'ui-dial',
  iconBen: 'ui-icon-ben',
  cardIcon: 'ui-card',
  droneIcon: 'ui-drone',
  bossIcon: 'ui-boss',
  achIcons: 'ui-ach-icons',
  vignette: 'ui-vignette',
  vilgax: 'story-vilgax',
  holoProjector: 'story-projector',
  crackedWall: 'prop-cracked-wall',
  lockedAlien: 'ui-locked-alien',
  touchJump: 'ui-touch-jump',
  touchPunch: 'ui-touch-punch',
  touchRoll: 'ui-touch-roll',
  touchPause: 'ui-touch-pause',
  // Road Trip.
  tilesDesert: 'tiles-desert',
  road: 'road-scroll',
  roadCap: 'road-cap',
  sunsetSky: 'bg-sunset-sky',
  duskSky: 'bg-dusk-sky',
  sun: 'bg-sun',
  farMesas: 'bg-far-mesas',
  nearButtes: 'bg-near-buttes',
  poles: 'bg-poles',
  scrub: 'bg-scrub',
  cactus: 'prop-cactus',
  cactusSmall: 'prop-cactus-small',
  diner: 'prop-diner',
  gasPump: 'prop-gas-pump',
  smoothyStand: 'prop-smoothy-stand',
  billboard: 'prop-billboard',
  roadSign: 'prop-road-sign',
  mileMarker: 'prop-mile-marker',
  bridgeEnd: 'prop-bridge-end',
  girder: 'prop-girder',
  guardrail: 'prop-guardrail',
  tumbleweed: 'prop-tumbleweed',
  skull: 'prop-skull',
  barrel: 'prop-barrel',
  carWreck: 'prop-car-wreck',
  poleSign: 'prop-pole-sign',
  garage: 'prop-garage',
  shed: 'prop-shed',
  neon: 'prop-neon',
  haulerWreck: 'prop-hauler-wreck',
  fence: 'prop-fence',
  rustbucket: 'vehicle-rustbucket',
  convoy: 'vehicle-convoy',
  haulerCab: 'vehicle-hauler-cab',
  haulerTrailer: 'vehicle-hauler-trailer',
  tire: 'prop-tire',
  rbTruck: 'boss-rb-truck',
  rbWheel: 'boss-rb-wheel',
  rbLegs: 'boss-rb-legs',
  rbTorso: 'boss-rb-torso',
  rbArm: 'boss-rb-arm',
  rbPlate: 'boss-rb-plate',
  pothole: 'prop-pothole',
  portraitMax: 'portrait-max',
  portraitGwen: 'portrait-gwen',
  portraitBen: 'portrait-ben',
  portraitVilgax: 'portrait-vilgax',
  // Dr. Animo.
  slimeGlob: 'fx-slime-glob',
  spitGlob: 'fx-spit-glob',
  puddle: 'fx-puddle',
  rat: 'mutant-rat',
  roach: 'mutant-roach',
  lurker: 'mutant-lurker',
  brute: 'mutant-brute',
  bat: 'mutant-bat',
  tilesMuseum: 'tiles-museum',
  citySky: 'bg-city-sky',
  city: 'bg-city',
  hallWall: 'bg-hall-wall',
  labWall: 'bg-lab-wall',
  mutagenPool: 'fx-mutagen-pool',
  tarPool: 'fx-tar-pool',
  lampPost: 'prop-lamp-post',
  museumFacade: 'prop-museum-facade',
  trex: 'prop-trex',
  mammoth: 'prop-mammoth',
  whale: 'prop-whale',
  pterosaur: 'prop-pterosaur',
  displayCase: 'prop-display-case',
  stuffedBear: 'prop-stuffed-bear',
  banner: 'prop-banner',
  painting: 'prop-painting',
  velvetRope: 'prop-velvet-rope',
  bench: 'prop-bench',
  exitSign: 'prop-exit-sign',
  tarSign: 'prop-tar-sign',
  meteorite: 'prop-meteorite',
  mutagenTank: 'prop-mutagen-tank',
  cage: 'prop-cage',
  labConsole: 'prop-lab-console',
  pipes: 'prop-pipes',
  staffDoor: 'prop-staff-door',
  column: 'prop-column',
  vines: 'prop-vines',
  glass: 'prop-glass',
  animo: 'char-animo',
  portraitAnimo: 'portrait-animo',
  frog: 'boss-frog',
  tongue: 'boss-frog-tongue',
  kevin: 'char-kevin',
  arcade: 'prop-arcade',
  portraitKevin: 'portrait-kevin',
  guard: 'char-guard',
  // Kevin 11: downtown, the arcade, the subway, the substation.
  tilesCity: 'tiles-city',
  citySkyDusk: 'bg-dusk-sky-city',
  skylineFar: 'bg-skyline-far',
  skylineNear: 'bg-skyline-near',
  arcadeWall: 'bg-arcade-wall',
  lairWall: 'bg-lair-wall',
  subwayWall: 'bg-subway-wall',
  tunnelWall: 'bg-tunnel-wall',
  substationWall: 'bg-substation-wall',
  storefront: 'prop-storefront',
  arcadeFront: 'prop-arcade-front',
  streetLamp: 'prop-street-lamp',
  powerPole: 'prop-power-pole',
  newsstand: 'prop-newsstand',
  hydrant: 'prop-hydrant',
  trashCan: 'prop-trash-can',
  neonSign: 'prop-neon-sign',
  prizeCounter: 'prop-prize-counter',
  ticketMachine: 'prop-ticket-machine',
  clawMachine: 'prop-claw-machine',
  skeeBall: 'prop-skee-ball',
  bandStage: 'prop-band-stage',
  breakerBox: 'prop-breaker-box',
  poster: 'prop-poster',
  laserBarrier: 'prop-laser-barrier',
  uvLight: 'prop-uv-light',
  stationSign: 'prop-station-sign',
  subwayMap: 'prop-subway-map',
  pillar: 'prop-pillar',
  turnstile: 'prop-turnstile',
  tunnelLight: 'prop-tunnel-light',
  cables: 'prop-cables',
  transformer: 'prop-transformer',
  generator: 'prop-generator',
  warningSign: 'prop-warning-sign',
  securityLaser: 'prop-security-laser',
  sealedDoor: 'prop-sealed-door',
  catwalkRail: 'prop-catwalk-rail',
  rails: 'prop-rails',
  teslaCoil: 'prop-tesla-coil',
  sumoBen: 'arcade-sumo-ben',
  sumoKev: 'arcade-sumo-kev',
  sumoRing: 'arcade-sumo-ring',
  // Kevin 11: machines.
  shutter: 'tech-shutter',
  shutterBar: 'tech-shutter-bar',
  keypad: 'tech-keypad',
  turretBase: 'tech-turret-base',
  turretHead: 'tech-turret-head',
  liftDeck: 'tech-lift-deck',
  cart: 'tech-cart',
  cartBarrier: 'tech-cart-barrier',
  cabinet: 'tech-cabinet',
  sumoCabinet: 'tech-sumo-cabinet',
  trainCar: 'tech-train-car',
  trackBed: 'fx-track-bed',
  warnLamp: 'tech-warn-lamp',
  mascot: 'robot-mascot',
  trackbot: 'robot-trackbot',
  sparkWisp: 'enemy-spark',
  kevinActor: 'char-kevin-actor',
  portraitKevinGrin: 'portrait-kevin-grin',
  chimera: 'boss-chimera',
} as const;

export type TextureKey = (typeof TEX)[keyof typeof TEX];

export type { AnimDef, AssetDef };

/** Barricade sizes (tiles) used by level data; each gets its own texture. */
export const BARRICADE_SIZES: ReadonlyArray<readonly [number, number]> = [
  [2, 4],
  [2, 3],
];
export const barricadeKey = (w: number, h: number) => `prop-barricade-${w}x${h}`;

/** KEVIN 11's overlays: one per alien he can wear a piece of. */
export const chimeraPartKey = (part: kevin.ChimeraPart) => `boss-chimera-${part}`;

export const ASSETS: AssetDef[] = [
  sheet(TEX.ben, BEN_FRAME.w, BEN_FRAME.h, BEN_FRAME_COUNT, (pc, f) => drawBen(pc, f, true)),
  sheet(TEX.benNoWatch, BEN_FRAME.w, BEN_FRAME.h, BEN_FRAME_COUNT, (pc, f) => drawBen(pc, f, false)),
  sheet(TEX.scout, 20, 16, 3, drawScout),
  sheet(TEX.striker, 22, 18, 3, drawStriker),
  sheet(TEX.gunner, 28, 20, 3, drawGunner),
  sheet(TEX.armored, 30, 24, 7, drawArmored),
  sheet(TEX.hornet, 18, 12, 3, drawHornet),
  one(TEX.bossHull, BOSS_HULL.w, BOSS_HULL.h, drawBossHull),
  one(TEX.bossPlate, 32, 24, drawBossPlate),
  one(TEX.bossTopPlate, 46, 12, drawBossTopPlate),
  sheet(TEX.bossEye, 27, 27, 4, drawBossEye),
  sheet(TEX.bossArm, 15, 34, 2, drawBossArm),

  sheet(TEX.tiles, 16, 16, TILESET_FRAME_COUNT, world.drawTile),
  sheet(TEX.tilesSim, 16, 16, TILESET_FRAME_COUNT, world.drawSimTile),
  one(TEX.simSky, 8, 360, world.drawSimSky),
  one(TEX.simGrid, 64, 64, world.drawSimGrid),
  one(TEX.simTowers, 256, 120, world.drawSimTowers),
  one(TEX.boulder, 18, 16, props.drawBoulder),
  one(TEX.dummy, 20, 32, props.drawDummy),
  one(TEX.sky, 8, 360, world.drawSky),
  one(TEX.stars, 320, 200, world.drawStars),
  one(TEX.moon, 40, 40, world.drawMoon),
  one(TEX.mountains, 512, 140, world.drawMountains),
  one(TEX.pinesFar, 384, 150, (pc) => world.drawPines(pc, 0)),
  one(TEX.pinesMid, 384, 200, (pc) => world.drawPines(pc, 1)),
  one(TEX.fog, 320, 80, world.drawFog),
  one(TEX.trunks, 320, 40, world.drawTrunks),
  one(TEX.crashGlow, 256, 128, world.drawCrashGlow),

  one(TEX.rv, 96, 48, props.drawRv),
  sheet(TEX.tent, 41, 29, 2, props.drawTent),
  one(TEX.campfire, 21, 12, props.drawCampfire),
  one(TEX.log, 27, 10, props.drawLog),
  one(TEX.sign, 16, 19, props.drawSign),
  sheet(TEX.bush, 20, 13, 2, props.drawBush),
  sheet(TEX.rock, 14, 10, 2, props.drawRock),
  one(TEX.stump, 13, 12, props.drawStump),
  sheet(TEX.grass, 8, 6, 2, props.drawGrass),
  one(TEX.mushroom, 9, 6, props.drawMushroom),
  one(TEX.crater, 48, 8, props.drawCrater),
  one(TEX.wreck, 48, 33, props.drawWreck),
  one(TEX.debris, 22, 13, props.drawDebris),
  one(TEX.burningLogs, 17, 10, props.drawBurningLogs),
  sheet(TEX.pod, 25, 17, 2, props.drawPod),
  one(TEX.omnitrixItem, 10, 10, props.drawOmnitrixItem),
  sheet(TEX.checkpoint, 13, 29, 2, props.drawCheckpoint),
  one(TEX.smoothy, 14, 19, props.drawSmoothy),
  sheet(TEX.card, 12, 16, 2, props.drawCard),
  sheet(TEX.jammer, 25, 63, 4, props.drawJammer),
  sheet(TEX.gate, 8, 16, 4, (pc, f) => props.drawEnergyWall(pc, f, P.jammer, P.jammerDark)),
  sheet(TEX.arenaWall, 8, 16, 4, (pc, f) => props.drawEnergyWall(pc, f, P.enemy, P.enemyDark)),
  ...BARRICADE_SIZES.map(([w, h]) => one(barricadeKey(w, h), w * 16, h * 16, (pc) => props.drawBarricade(pc, w * 16, h * 16))),

  one(TEX.soft, 16, 16, fx.drawSoft),
  one(TEX.light, 64, 64, fx.drawLight),
  one(TEX.px, 2, 2, fx.drawPixel),
  one(TEX.spark, 3, 3, fx.drawSpark),
  one(TEX.ember, 3, 3, fx.drawEmber),
  one(TEX.smoke, 12, 12, fx.drawSmoke),
  one(TEX.ring, 64, 64, fx.drawRing),
  one(TEX.rays, 128, 128, fx.drawRays),
  one(TEX.hourglass, 64, 64, fx.drawHourglass),
  sheet(TEX.fireball, 14, 12, 3, fx.drawFireball),
  one(TEX.laser, 12, 5, fx.drawLaser),
  one(TEX.bossBolt, 10, 10, fx.drawBossBolt),
  sheet(TEX.shockwave, 22, 14, 3, fx.drawShockwave),
  sheet(TEX.wave, 22, 14, 3, fx.drawWave),
  one(TEX.streak, 28, 1, fx.drawStreak),
  one(TEX.crack, 48, 12, fx.drawCrack),
  one(TEX.needle, 9, 3, fx.drawNeedle),
  one(TEX.shell, 10, 10, fx.drawShell),
  sheet(TEX.bomb, 9, 11, 2, fx.drawBomb),
  one(TEX.reticle, 16, 16, fx.drawReticle),
  one(TEX.beam, 4, 20, fx.drawBeam),
  sheet(TEX.debrisBits, 3, 3, 4, fx.drawDebrisBits),
  one(TEX.leaf, 2, 2, fx.drawLeaf),
  one(TEX.shadow, 48, 10, fx.drawShadow),
  sheet(TEX.water, 32, 64, 4, fx.drawWater),
  one(TEX.whitePx, 4, 4, fx.drawAfterimage),

  sheet(TEX.heart, 9, 8, 3, ui.drawHeart),
  one(TEX.dialFrame, 44, 44, ui.drawDialFrame),
  one(TEX.iconBen, 12, 12, ui.drawBenIcon),
  sheet(TEX.cardIcon, 9, 11, 2, ui.drawCardIcon),
  one(TEX.droneIcon, 11, 8, ui.drawDroneIcon),
  one(TEX.bossIcon, 14, 10, ui.drawBossIcon),
  sheet(TEX.achIcons, 12, 12, 5, ui.drawAchievementIcon),
  one(TEX.vignette, 320, 180, ui.drawVignette),
  one(TEX.vilgax, story.VILGAX_SIZE.w, story.VILGAX_SIZE.h, story.drawVilgax),
  one(TEX.holoProjector, 19, 10, story.drawHoloProjector),
  one(TEX.crackedWall, 16, 48, story.drawCrackedWall),
  one(TEX.lockedAlien, 42, 44, story.drawLockedSilhouette),
  one(TEX.touchJump, 16, 16, ui.drawTouchJump),
  one(TEX.touchPunch, 16, 16, ui.drawTouchPunch),
  one(TEX.touchRoll, 16, 16, ui.drawTouchRoll),
  one(TEX.touchPause, 16, 16, ui.drawTouchPause),
  ...SILHOUETTE_ASSETS,

  sheet(TEX.tilesDesert, 16, 16, TILESET_FRAME_COUNT, hw.drawDesertTile),
  one(TEX.road, 64, 160, hw.drawRoad),
  one(TEX.roadCap, 64, 16, hw.drawRoadCap),
  one(TEX.sunsetSky, 8, 360, hw.drawSunsetSky),
  one(TEX.duskSky, 8, 360, hw.drawDuskSky),
  one(TEX.sun, 72, 72, hw.drawSun),
  one(TEX.farMesas, 512, 140, hw.drawFarMesas),
  one(TEX.nearButtes, 384, 170, hw.drawNearButtes),
  one(TEX.poles, 256, 110, hw.drawPoles),
  one(TEX.scrub, 320, 40, hw.drawScrub),
  one(TEX.cactus, 22, 40, hw.drawCactus),
  one(TEX.cactusSmall, 14, 14, hw.drawCactusSmall),
  one(TEX.diner, 120, 88, hw.drawDiner),
  one(TEX.gasPump, 14, 26, hw.drawGasPump),
  one(TEX.smoothyStand, 48, 56, hw.drawSmoothyStand),
  sheet(TEX.billboard, 96, 64, 2, hw.drawBillboard),
  one(TEX.roadSign, 16, 28, hw.drawRoadSign),
  one(TEX.mileMarker, 8, 16, hw.drawMileMarker),
  one(TEX.bridgeEnd, 48, 40, hw.drawBridgeEnd),
  one(TEX.girder, 62, 26, hw.drawGirder),
  one(TEX.guardrail, 32, 12, hw.drawGuardrail),
  one(TEX.tumbleweed, 14, 12, hw.drawTumbleweed),
  one(TEX.skull, 14, 8, hw.drawSkull),
  one(TEX.barrel, 12, 16, hw.drawBarrel),
  one(TEX.carWreck, 56, 26, hw.drawCarWreck),
  one(TEX.poleSign, 40, 192, hw.drawPoleSign),
  one(TEX.garage, 96, 64, hw.drawGarage),
  one(TEX.shed, 80, 64, hw.drawShed),
  sheet(TEX.neon, 52, 24, 2, hw.drawNeon),
  one(TEX.haulerWreck, 160, 56, hw.drawHaulerWreck),
  one(TEX.fence, 32, 14, hw.drawFence),
  sheet(TEX.rustbucket, veh.RUSTBUCKET.w, veh.RUSTBUCKET.h, 3, veh.drawRustbucket),
  sheet(TEX.convoy, veh.CONVOY.w, veh.CONVOY.h, 4, veh.drawConvoyTruck),
  sheet(TEX.haulerCab, veh.HAULER_CAB.w, veh.HAULER_CAB.h, 2, veh.drawHaulerCab),
  sheet(TEX.haulerTrailer, veh.HAULER_TRAILER.w, veh.HAULER_TRAILER.h, 2, veh.drawHaulerTrailer),
  one(TEX.tire, 16, 16, veh.drawTire),
  sheet(TEX.rbTruck, rb.RB_TRUCK.w, rb.RB_TRUCK.h, 4, rb.drawRbTruck),
  sheet(TEX.rbWheel, rb.RB_WHEEL.w, rb.RB_WHEEL.h, 3, rb.drawRbWheel),
  sheet(TEX.rbLegs, rb.RB_LEGS.w, rb.RB_LEGS.h, 4, rb.drawRbLegs),
  sheet(TEX.rbTorso, rb.RB_TORSO.w, rb.RB_TORSO.h, 3, rb.drawRbTorso),
  one(TEX.rbArm, rb.RB_ARM.w, rb.RB_ARM.h, rb.drawRbArm),
  sheet(TEX.rbPlate, rb.RB_PLATE.w, rb.RB_PLATE.h, 2, rb.drawRbPlate),
  one(TEX.pothole, 30, 6, veh.drawPothole),
  one(TEX.portraitMax, portraits.PORTRAIT.w, portraits.PORTRAIT.h, portraits.drawPortraitMax),
  one(TEX.portraitGwen, portraits.PORTRAIT.w, portraits.PORTRAIT.h, portraits.drawPortraitGwen),
  one(TEX.portraitBen, portraits.PORTRAIT.w, portraits.PORTRAIT.h, portraits.drawPortraitBen),
  one(TEX.portraitVilgax, portraits.PORTRAIT.w, portraits.PORTRAIT.h, portraits.drawPortraitVilgax),
  sheet(TEX.slimeGlob, 12, 12, 3, goo.drawSlimeGlob),
  sheet(TEX.spitGlob, 12, 12, 3, goo.drawSpitGlob),
  sheet(TEX.puddle, 32, 6, 3, goo.drawPuddle),
  sheet(TEX.rat, mut.MUTANT_SIZES.rat.w, mut.MUTANT_SIZES.rat.h, 4, mut.drawRat),
  sheet(TEX.roach, mut.MUTANT_SIZES.roach.w, mut.MUTANT_SIZES.roach.h, 3, mut.drawRoach),
  sheet(TEX.lurker, mut.MUTANT_SIZES.lurker.w, mut.MUTANT_SIZES.lurker.h, 4, mut.drawLurker),
  sheet(TEX.brute, mut.MUTANT_SIZES.brute.w, mut.MUTANT_SIZES.brute.h, 4, mut.drawBrute),
  sheet(TEX.bat, mut.MUTANT_SIZES.bat.w, mut.MUTANT_SIZES.bat.h, 4, mut.drawBat),
  sheet(TEX.tilesMuseum, 16, 16, TILESET_FRAME_COUNT, mus.drawMuseumTile),
  one(TEX.citySky, 8, 360, mus.drawCitySky),
  one(TEX.city, 384, 120, mus.drawCity),
  one(TEX.hallWall, 128, 192, mus.drawHallWall),
  one(TEX.labWall, 128, 192, mus.drawLabWall),
  sheet(TEX.mutagenPool, 32, 64, 4, goo.drawMutagenPool),
  sheet(TEX.tarPool, 32, 64, 4, goo.drawTarPool),
  one(TEX.lampPost, 12, 56, mus.drawLampPost),
  one(TEX.museumFacade, 240, 150, mus.drawMuseumFacade),
  one(TEX.trex, 150, 110, mus.drawTrex),
  one(TEX.mammoth, 110, 80, mus.drawMammoth),
  one(TEX.whale, 220, 60, mus.drawWhale),
  one(TEX.pterosaur, 70, 30, mus.drawPterosaur),
  one(TEX.displayCase, 32, 30, mus.drawDisplayCase),
  one(TEX.stuffedBear, 30, 44, mus.drawStuffedBear),
  one(TEX.banner, 24, 56, mus.drawBanner),
  one(TEX.painting, 40, 30, mus.drawPainting),
  one(TEX.velvetRope, 32, 16, mus.drawVelvetRope),
  one(TEX.bench, 32, 12, mus.drawBench),
  one(TEX.exitSign, 20, 10, mus.drawExitSign),
  one(TEX.tarSign, 40, 30, mus.drawTarSign),
  one(TEX.meteorite, 40, 44, mus.drawMeteorite),
  one(TEX.mutagenTank, 28, 56, mus.drawMutagenTank),
  one(TEX.cage, 36, 32, mus.drawCage),
  one(TEX.labConsole, 48, 34, mus.drawLabConsole),
  one(TEX.pipes, 64, 24, mus.drawPipes),
  one(TEX.staffDoor, 24, 40, mus.drawStaffDoor),
  one(TEX.column, 24, 112, mus.drawColumn),
  one(TEX.vines, 16, 16, mus.drawVines),
  one(TEX.glass, 16, 8, mus.drawGlass),
  sheet(TEX.animo, animo.ANIMO_FRAME.w, animo.ANIMO_FRAME.h, animo.ANIMO_FRAME_COUNT, animo.drawAnimo),
  one(TEX.portraitAnimo, portraits.PORTRAIT.w, portraits.PORTRAIT.h, animo.drawPortraitAnimo),
  sheet(TEX.frog, animo.FROG_FRAME.w, animo.FROG_FRAME.h, animo.FROG_FRAME_COUNT, animo.drawFrog),
  sheet(TEX.tongue, 8, 6, 2, animo.drawTongue),
  sheet(TEX.kevin, animo.KEVIN_FRAME.w, animo.KEVIN_FRAME.h, 3, animo.drawKevin),
  sheet(TEX.arcade, 26, 44, 2, animo.drawArcade),
  one(TEX.portraitKevin, portraits.PORTRAIT.w, portraits.PORTRAIT.h, animo.drawPortraitKevin),
  sheet(TEX.guard, 20, 30, 2, animo.drawGuard),
  sheet(TEX.tilesCity, 16, 16, TILESET_FRAME_COUNT, city.drawCityTile),
  one(TEX.citySkyDusk, 8, 360, city.drawDuskSky),
  one(TEX.skylineFar, 384, 140, city.drawSkylineFar),
  one(TEX.skylineNear, 384, 170, city.drawSkylineNear),
  one(TEX.arcadeWall, 128, 192, city.drawArcadeWall),
  one(TEX.lairWall, 128, 192, city.drawLairWall),
  one(TEX.subwayWall, 128, 192, city.drawSubwayWall),
  one(TEX.tunnelWall, 128, 192, city.drawTunnelWall),
  one(TEX.substationWall, 128, 192, city.drawSubstationWall),
  sheet(TEX.storefront, 96, 72, 3, city.drawStorefront),
  one(TEX.arcadeFront, 112, 100, city.drawArcadeFront),
  one(TEX.streetLamp, 14, 64, city.drawStreetLamp),
  one(TEX.powerPole, 20, 120, city.drawPowerPole),
  one(TEX.newsstand, 32, 30, city.drawNewsstand),
  one(TEX.hydrant, 10, 13, city.drawHydrant),
  one(TEX.trashCan, 12, 16, city.drawTrashCan),
  sheet(TEX.neonSign, 48, 20, 3, city.drawNeonSign),
  one(TEX.prizeCounter, 96, 34, city.drawPrizeCounter),
  one(TEX.ticketMachine, 16, 34, city.drawTicketMachine),
  one(TEX.clawMachine, 64, 56, city.drawClawMachine),
  one(TEX.skeeBall, 48, 34, city.drawSkeeBall),
  one(TEX.bandStage, 144, 80, city.drawBandStage),
  sheet(TEX.breakerBox, 24, 32, 2, city.drawBreakerBox),
  sheet(TEX.poster, 22, 30, 3, city.drawPoster),
  sheet(TEX.laserBarrier, 32, 32, 2, city.drawLaserBarrier),
  one(TEX.uvLight, 16, 8, city.drawUvLight),
  one(TEX.stationSign, 96, 18, city.drawStationSign),
  one(TEX.subwayMap, 48, 32, city.drawSubwayMap),
  one(TEX.pillar, 16, 96, city.drawPillar),
  one(TEX.turnstile, 24, 26, city.drawTurnstile),
  one(TEX.tunnelLight, 10, 10, city.drawTunnelLight),
  one(TEX.cables, 64, 20, city.drawCables),
  one(TEX.transformer, 40, 48, city.drawTransformer),
  one(TEX.generator, 56, 44, city.drawGenerator),
  one(TEX.warningSign, 18, 18, city.drawWarningSign),
  one(TEX.securityLaser, 20, 48, city.drawSecurityLaser),
  one(TEX.sealedDoor, 26, 48, city.drawSealedDoor),
  one(TEX.catwalkRail, 32, 10, city.drawCatwalkRail),
  one(TEX.rails, 32, 8, city.drawRails),
  sheet(TEX.teslaCoil, 28, 80, 2, city.drawTeslaCoil),
  sheet(TEX.sumoBen, sumo.SUMO_FRAME.w, sumo.SUMO_FRAME.h, sumo.SUMO_FRAME_COUNT, sumo.drawSumo(0)),
  sheet(TEX.sumoKev, sumo.SUMO_FRAME.w, sumo.SUMO_FRAME.h, sumo.SUMO_FRAME_COUNT, sumo.drawSumo(1)),
  one(TEX.sumoRing, 240, 28, sumo.drawSumoRing),
  one(TEX.shutter, 16, 16, tech.drawShutter),
  one(TEX.shutterBar, 16, 5, tech.drawShutterBar),
  sheet(TEX.keypad, 10, 16, 2, tech.drawKeypad),
  one(TEX.turretBase, 22, 14, tech.drawTurretBase),
  sheet(TEX.turretHead, 24, 14, 3, tech.drawTurretHead),
  one(TEX.liftDeck, 16, 10, tech.drawLiftDeck),
  sheet(TEX.cart, 48, 30, 2, tech.drawCart),
  one(TEX.cartBarrier, 16, 48, tech.drawBarrier),
  sheet(TEX.cabinet, 28, 46, tech.CABINET_SPENT_FRAME + 1, tech.drawCabinet),
  sheet(TEX.sumoCabinet, 34, 52, 4, tech.drawSumoCabinet),
  sheet(TEX.trainCar, 128, 52, 2, tech.drawTrainCar),
  one(TEX.trackBed, 32, 64, tech.drawTrackBed),
  sheet(TEX.warnLamp, 8, 10, 2, tech.drawWarnLamp),
  sheet(TEX.mascot, robots.MASCOT_FRAME.w, robots.MASCOT_FRAME.h, 4, robots.drawMascot),
  sheet(TEX.trackbot, robots.TRACKBOT_FRAME.w, robots.TRACKBOT_FRAME.h, 4, robots.drawTrackbot),
  sheet(TEX.sparkWisp, 14, 14, 2, robots.drawSparkWisp),
  sheet(TEX.kevinActor, kevin.KEVIN_ACTOR_FRAME.w, kevin.KEVIN_ACTOR_FRAME.h, kevin.KEVIN_ACTOR_FRAME_COUNT, kevin.drawKevinActor),
  one(TEX.portraitKevinGrin, portraits.PORTRAIT.w, portraits.PORTRAIT.h, kevin.drawPortraitKevinGrin),
  sheet(TEX.chimera, kevin.CHIMERA_FRAME.w, kevin.CHIMERA_FRAME.h, kevin.CHIMERA_FRAME_COUNT, kevin.drawChimeraBase),
  ...kevin.CHIMERA_PARTS.map((p) => sheet(chimeraPartKey(p), kevin.CHIMERA_FRAME.w, kevin.CHIMERA_FRAME.h, kevin.CHIMERA_FRAME_COUNT, kevin.drawChimeraPart(p))),
];

const benAnims = (prefix: string, texture: string): AnimDef[] => [
  { key: `${prefix}-idle`, texture, frames: BEN_FRAMES.idle, frameRate: 3, repeat: -1 },
  { key: `${prefix}-run`, texture, frames: BEN_FRAMES.run, frameRate: 14, repeat: -1 },
  { key: `${prefix}-jump`, texture, frames: BEN_FRAMES.jump, frameRate: 1, repeat: 0 },
  { key: `${prefix}-fall`, texture, frames: BEN_FRAMES.fall, frameRate: 1, repeat: 0 },
  { key: `${prefix}-punch`, texture, frames: BEN_FRAMES.punch, frameRate: 22, repeat: 0 },
  { key: `${prefix}-roll`, texture, frames: BEN_FRAMES.roll, frameRate: 16, repeat: -1 },
  { key: `${prefix}-hurt`, texture, frames: BEN_FRAMES.hurt, frameRate: 1, repeat: 0 },
  { key: `${prefix}-watch`, texture, frames: BEN_FRAMES.watch, frameRate: 1, repeat: 0 },
];

export const ANIMS: AnimDef[] = [
  ...benAnims('ben', TEX.ben),
  ...benAnims('bennw', TEX.benNoWatch),
  { key: 'scout-idle', texture: TEX.scout, frames: [0, 1], frameRate: 10, repeat: -1 },
  { key: 'striker-idle', texture: TEX.striker, frames: [0, 1], frameRate: 8, repeat: -1 },
  { key: 'gunner-idle', texture: TEX.gunner, frames: [0, 1], frameRate: 4, repeat: -1 },
  { key: 'armored-idle', texture: TEX.armored, frames: [0, 1], frameRate: 6, repeat: -1 },
  { key: 'armored-cracked', texture: TEX.armored, frames: [3, 4], frameRate: 6, repeat: -1 },
  { key: 'armored-exposed', texture: TEX.armored, frames: [5, 6], frameRate: 12, repeat: -1 },
  { key: 'hornet-idle', texture: TEX.hornet, frames: [0, 1], frameRate: 24, repeat: -1 },
  { key: 'fireball-spin', texture: TEX.fireball, frames: [0, 1, 2], frameRate: 18, repeat: -1 },
  { key: 'shockwave-roll', texture: TEX.shockwave, frames: [0, 1, 2], frameRate: 14, repeat: -1 },
  { key: 'wave-roll', texture: TEX.wave, frames: [0, 1, 2], frameRate: 16, repeat: -1 },
  { key: 'bomb-blink', texture: TEX.bomb, frames: [0, 1], frameRate: 10, repeat: -1 },
  { key: 'water-flow', texture: TEX.water, frames: [0, 1, 2, 3], frameRate: 6, repeat: -1 },
  { key: 'mutagen-flow', texture: TEX.mutagenPool, frames: [0, 1, 2, 3], frameRate: 6, repeat: -1 },
  { key: 'tar-flow', texture: TEX.tarPool, frames: [0, 1, 2, 3], frameRate: 3, repeat: -1 },
  { key: 'gate-hum', texture: TEX.gate, frames: [0, 1, 2, 3], frameRate: 12, repeat: -1 },
  { key: 'arena-hum', texture: TEX.arenaWall, frames: [0, 1, 2, 3], frameRate: 12, repeat: -1 },
  { key: 'jammer-pulse', texture: TEX.jammer, frames: [0, 0, 1], frameRate: 4, repeat: -1 },
  { key: 'boss-arm-snap', texture: TEX.bossArm, frames: [0, 1, 0], frameRate: 10, repeat: 0 },
  { key: 'rustbucket-drive', texture: TEX.rustbucket, frames: [0, 1], frameRate: 14, repeat: -1 },
  { key: 'convoy-drive', texture: TEX.convoy, frames: [0, 1], frameRate: 14, repeat: -1 },
  { key: 'rb-drive', texture: TEX.rbTruck, frames: [0, 1], frameRate: 10, repeat: -1 },
  { key: 'rb-wheel', texture: TEX.rbWheel, frames: [0, 1], frameRate: 16, repeat: -1 },
  { key: 'rb-walk', texture: TEX.rbLegs, frames: [1, 0, 2, 0], frameRate: 6, repeat: -1 },
  { key: 'slime-wobble', texture: TEX.slimeGlob, frames: [0, 1, 2, 1], frameRate: 14, repeat: -1 },
  { key: 'spit-wobble', texture: TEX.spitGlob, frames: [0, 1, 2, 1], frameRate: 12, repeat: -1 },
  { key: 'puddle-bubble', texture: TEX.puddle, frames: [0, 1, 2], frameRate: 5, repeat: -1 },
  { key: 'rat-idle', texture: TEX.rat, frames: [0, 1], frameRate: 4, repeat: -1 },
  { key: 'rat-run', texture: TEX.rat, frames: [0, 1], frameRate: 14, repeat: -1 },
  { key: 'roach-idle', texture: TEX.roach, frames: [0, 1], frameRate: 6, repeat: -1 },
  { key: 'lurker-idle', texture: TEX.lurker, frames: [0, 0, 0, 1], frameRate: 3, repeat: -1 },
  { key: 'brute-idle', texture: TEX.brute, frames: [0, 1], frameRate: 3, repeat: -1 },
  { key: 'bat-idle', texture: TEX.bat, frames: [0, 1], frameRate: 12, repeat: -1 },
  { key: 'animo-idle', texture: TEX.animo, frames: [0, 1], frameRate: 3, repeat: -1 },
  { key: 'animo-walk', texture: TEX.animo, frames: [4, 0, 5, 0], frameRate: 8, repeat: -1 },
  { key: 'guard-run', texture: TEX.guard, frames: [0, 1], frameRate: 12, repeat: -1 },
  { key: 'frog-idle', texture: TEX.frog, frames: [0, 1], frameRate: 3, repeat: -1 },
  { key: 'neon-flicker', texture: TEX.neon, frames: [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0], frameRate: 8, repeat: -1 },
  ...[0, 1, 2, 3].map((v) => ({ key: `cabinet-attract-${v}`, texture: TEX.cabinet, frames: [v * 2, v * 2 + 1], frameRate: 2 + v * 0.5, repeat: -1 })),
  { key: 'sumo-attract', texture: TEX.sumoCabinet, frames: [0, 1], frameRate: 2, repeat: -1 },
  { key: 'mascot-idle', texture: TEX.mascot, frames: [0, 1], frameRate: 2, repeat: -1 },
  { key: 'mascot-walk', texture: TEX.mascot, frames: [0, 1], frameRate: 5, repeat: -1 },
  { key: 'trackbot-idle', texture: TEX.trackbot, frames: [0, 1], frameRate: 4, repeat: -1 },
  { key: 'trackbot-roll', texture: TEX.trackbot, frames: [0, 1], frameRate: 12, repeat: -1 },
  { key: 'voltbot-idle', texture: TEX.trackbot, frames: [0, 1], frameRate: 6, repeat: -1 },
  { key: 'spark-idle', texture: TEX.sparkWisp, frames: [0, 1], frameRate: 14, repeat: -1 },
  ...(Object.entries(kevin.KEVIN_ACTOR_FRAMES) as Array<[string, readonly number[]]>).map(([name, frames]) => ({
    key: `kevin-${name}`,
    texture: TEX.kevinActor,
    frames,
    frameRate: name === 'run' ? 12 : name === 'idle' ? 3 : 10,
    repeat: name === 'idle' || name === 'run' || name === 'absorb' ? -1 : 0,
  })),
  { key: 'chimera-idle', texture: TEX.chimera, frames: [0, 1], frameRate: 4, repeat: -1 },
];
